version: '2'

services:
    web:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./php-fpm/app/laravel:/var/www/html/laravel
        links:
            - php-fpm

    php-fpm:
        build: ./php-fpm
        #volumes:
        #    - ./app/laravel:/var/www/html/laravel
        tty: true
        links:
            - mysql
            - redis

    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password

    redis:
        image: "redis:alpine"

